services:
  db:
    image: postgres:latest
    networks:
      - bp-invest-net
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./back
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9001:8081"
      - "9002:8080"
    networks:
      - bp-invest-net

  frontend:
    build: ./front
    ports:
      - "5173:5173"
    networks:
      - bp-invest-net

  ai-analysis:
    build: ./ai_analysis
    networks:
      - bp-invest-net

networks:
  bp-invest-net: