--liquibase formatted sql

--changeset BiGPiG:1
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username      VARCHAR UNIQUE NOT NULL,
    password      VARCHAR NOT NULL,
    email         VARCHAR UNIQUE
);

--changeset BiGPiG:2
CREATE TABLE IF NOT EXISTS roles (
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR NOT NULL UNIQUE
);

--changeset BiGPiG:3
CREATE TABLE IF NOT EXISTS users_roles (
    user_id       BIGINT NOT NULL,
    role_id       INT NOT NULL,
    PRIMARY KEY   (user_id, role_id),
    FOREIGN KEY   (user_id) REFERENCES users (id),
    FOREIGN KEY   (role_id) REFERENCES  roles (id)
);

--changeset BiGPiG:4
INSERT INTO roles (name) values ('ROLE_USER');

--changeset BiGPiG:5
INSERT INTO users (username, password) VALUES (
    'admin',
    '$2a$12$C5/6JUBQ3/aNqMbcbs.lL.SBzM8Y9VH2oMDlGKjjr/1NLT3Npzw66'
);

--changeset BiGPiG:6
INSERT INTO users_roles (user_id, role_id) VALUES (
    1, 1
);